#!/bin/bash
remplacement='sed -e s/\[[[:alpha:][:space:]_-]*\][[:space:]\.]*//'
for f in *.*
do
    echo "transforme" $f "en " $(echo $f | $remplacement)
    mv "$f" "$(echo $f | $remplacement)"
done
